### ISSUE TITLE
Is `eslintConfig` from `package.json` considered?

### ISSUE THREAD

**Issue by sarbbottam** [kentcdodds/eslint-find-new-rules#28] opened 2016-03-28 17:49 UTC
When no `path/to/eslint-config` is passed to [`bin.js`](https://github.com/kentcdodds/eslint-find-new-rules/blob/master/bin.js), it fallbacks to [`require('package.json').main`](https://github.com/kentcdodds/eslint-find-new-rules/blob/master/bin-utils.js#L22).

Looks like, for example this [`eslintConfig`](https://github.com/kentcdodds/eslint-find-new-rules/blob/master/package.json#L50-L58), is not being taken care.

Does `eslint`takes it into consideration by `default`?

**Comment by kentcdodds** [comment] 2016-03-28 19:31
Yes, eslint does. Can you show a specific reproduceable example where it's not?

This package was originally intended for config repos, which is why it defaults to the `package.json`.main.

**Comment by sarbbottam** [comment] 2016-03-28 20:09
In this repo, I see a difference in output between `node bin.js package.json` and `node bin.js`.
If I pass `package.json` it takes `eslintConfig` in the consideration, otherwise not.

Am I missing something?

**Comment by kentcdodds** [comment] 2016-03-28 20:11
To be perfectly honest, so much has happened to this repo I don't even know what should be happening anymore :sweat_smile: `¯\_(ツ)_/¯`

**Comment by ta2edchimp** [comment] 2016-03-28 20:21
It works as intended if the output differs, generally speaking and considering this repo, as this repo is _not_ an ESLint config (the script referenced in package.json's main field does not contain any rule configurations)! It _should_ output all available default rules.

When pointing towards _any_ package.json directly, its `eslintConfig` field will be interpreted.

**Comment by ta2edchimp** [comment] 2016-03-29 14:01
I marked this as "FAQ" and think we should leave this issue open until we somehow point out this behaviour more precisely within the docs.

**Comment by kentcdodds** [comment] 2016-04-14 21:30
Closing because this module is no longer maintained, please use https://github.com/sarbbottam/eslint-find-rules

**Closed as completed by kentcdodds** 2016-04-14 21:30 UTC
Labels: FAQ
